### ISSUE TITLE
This popped up when I logged today

### ISSUE THREAD

**Issue by Wyr3d** [wow-rp-addons/XRP#22]
Message: Interface\AddOns\XRP\Backend\MSP.lua:52: Usage: GetAutoCompleteResults(text, numResults, cursorPosition, allowFullMatch, includeBitField, excludeBitField)
Time: Thu Dec 13 18:59:46 2018
Count: 1
Stack: Interface\AddOns\XRP\Backend\MSP.lua:52: Usage: GetAutoCompleteResults(text, numResults, cursorPosition, allowFullMatch, includeBitField, excludeBitField)
Interface\AddOns\XRP\Backend\MSP.lua:52: in function <Interface\AddOns\XRP\Backend\MSP.lua:46>
[C]: in function `xpcall'
Interface\AddOns\XRP\Backend\GameEvents.lua:70: in function <Interface\AddOns\XRP\Backend\GameEvents.lua:67>

Locals: <none>

**Comment by Beeps** [comment]
Looks like GetAutoCompleteResults had a new parameter jammed into the middle of it - allowFullMatch.
If you want to get dirty, you can change that line to 
` for i, character in ipairs(GetAutoCompleteResults("", 0, 1, true, AUTO_COMPLETE_ACCOUNT_CHARACTER, 0)) do`
Which will stop the error from happening. May or may not function as previously intended, since I'm not 100% clear how the "full match" feature worked before.

**Comment by Keazra** [comment]
I get these errors when I log in as well:

```
Message: Interface\AddOns\XRP\Interface\Viewer\Viewer.lua:484: <unnamed>:SetAllPoints(): Couldn't find region named 'XRPViewerTitleBg'
Time: Tue Jan  1 19:54:50 2019
Count: 1
Stack: Interface\AddOns\XRP\Interface\Viewer\Viewer.lua:484: <unnamed>:SetAllPoints(): Couldn't find region named 'XRPViewerTitleBg'
[C]: in function `SetAllPoints'
Interface\AddOns\XRP\Interface\Viewer\Viewer.lua:484: in function <Interface\AddOns\XRP\Interface\Viewer\Viewer.lua:468>
[C]: in function `xpcall'
Interface\AddOns\XRP\Backend\Settings\Settings.lua:126: in function <Interface\AddOns\XRP\Backend\Settings\Settings.lua:124>
[C]: in function `xpcall'
Interface\AddOns\XRP\Backend\GameEvents.lua:70: in function <Interface\AddOns\XRP\Backend\GameEvents.lua:67>
```

Locals: <none>

and

```
Message: Interface\AddOns\XRP\Backend\MSP.lua:52: Usage: GetAutoCompleteResults(text, numResults, cursorPosition, allowFullMatch, includeBitField, excludeBitField)
Time: Tue Jan  1 19:54:50 2019
Count: 1
Stack: Interface\AddOns\XRP\Backend\MSP.lua:52: Usage: GetAutoCompleteResults(text, numResults, cursorPosition, allowFullMatch, includeBitField, excludeBitField)
[C]: in function `GetAutoCompleteResults'
Interface\AddOns\XRP\Backend\MSP.lua:52: in function <Interface\AddOns\XRP\Backend\MSP.lua:46>
[C]: in function `xpcall'
Interface\AddOns\XRP\Backend\GameEvents.lua:70: in function <Interface\AddOns\XRP\Backend\GameEvents.lua:67>

Locals: <none>
```

They don't ever appear again but still, figured I'd show it off.

**Comment by Wyr3d** [comment]
@Beeps - which file is that line in?

**Comment by Wyr3d** [comment]
@Beeps I have edited it for found,and will see how it goes. FInger's crossed it works without issue :/

**Comment by Wyr3d** [comment]
@Beeps Hey there,

I edited the file as suggested earlier today, and I no longer get the lua errors. It appears to have fixed the issue, but I won't know for certain until after more extensive testing. Thanks for the help ^^
