### ISSUE TITLE
Icons for Glances don't work

### ISSUE THREAD

**Issue by blitzyflitzy294** [wow-rp-addons/XRP#27]
The icons for the glances won't let me change them from the Question Mark icon.  In fact, no icons even show up in the window where you select the icons.
I've also tried updating and reinstalling.

![image](https://user-images.githubusercontent.com/57328647/68090605-33f91c00-fe3b-11e9-9f03-8d334b53f724.png)

**Comment by Solanya** [comment]
Sorry I missed your ticket, didn't set things up properly. I should have fixed an issue with the glance icon selector not working properly with the latest version (v2.0.5), can you let me know if you still encounter it.

**Comment by blitzyflitzy294** [comment]
Hi,
I have been using TRP in the meantime.  I just reinstalled xrp to check to see if it would work now.  It still doesn't.  Here are some error codes that pop up if that's helpful!
Here is the Raw paste.  I'm attaching screenshots of it, too.



Message: ...e\AddOns\XRP\Libraries\LibRPMedia\LibRPMedia-1.0.lua:2: Missing dependency: LibStubTime: Thu Jan 16 17:49:43 2020Count: 1Stack: ...e\AddOns\XRP\Libraries\LibRPMedia\LibRPMedia-1.0.lua:2: Missing dependency: LibStub[string "=[C]"]: in function `assert'[string "@Interface\AddOns\XRP\Libraries\LibRPMedia\LibRPMedia-1.0.lua"]:2: in main chunk
Locals: (*temporary) = nil(*temporary) = "Missing dependency: LibStub"

Message: Interface\AddOns\XRP\Interface\Glances\Icons.lua:1: attempt to index global 'LibStub' (a nil value)Time: Thu Jan 16 17:49:43 2020Count: 1Stack: Interface\AddOns\XRP\Interface\Glances\Icons.lua:1: attempt to index global 'LibStub' (a nil value)[string "@Interface\AddOns\XRP\Interface\Glances\Icons.lua"]:1: in main chunk
Locals: (*temporary) = nil(*temporary) = nil(*temporary) = nil(*temporary) = nil(*temporary) = nil(*temporary) = nil(*temporary) = nil(*temporary) = nil(*temporary) = "attempt to index global 'LibStub' (a nil value)"



Message: (null)Time: Thu Jan 16 17:49:46 2020Count: 10

Message: Interface\AddOns\XRP\Interface\Editor\Glances.lua:184: bad argument #1 to 'ipairs' (table expected, got nil)Time: Thu Jan 16 17:50:03 2020Count: 1Stack: Interface\AddOns\XRP\Interface\Editor\Glances.lua:184: bad argument #1 to 'ipairs' (table expected, got nil)[string "=[C]"]: in function `ipairs'[string "@Interface\AddOns\XRP\Interface\Editor\Glances.lua"]:184: in function <Interface\AddOns\XRP\Interface\Editor\Glances.lua:177>[string "=[C]"]: ?
Locals: (*temporary) = nil(*temporary) = "table expected, got nil" = <function> defined =[C]:-1









 

    On Wednesday, January 15, 2020, 06:18:56 PM CST, Solanya <notifications@github.com> wrote:  
 
 
Sorry I missed your ticket, didn't set things up properly. I should have fixed an issue with the glance icon selector not working properly with the latest version (v2.0.5), can you let me know if you still encounter it.

**Comment by Solanya** [comment]
Something is wrong with your installation. Are you manually downloading the addon on CurseForge or using the Twitch App ?

**Comment by blitzyflitzy294** [comment]
I was using the twitch app. 

    On Thursday, January 16, 2020, 06:06:10 PM CST, Solanya <notifications@github.com> wrote:  
 
 
Something is wrong with your installation. Are you manually downloading the addon on CurseForge or using the Twitch App ?

**Comment by Solanya** [comment]
I guess you can always try to install the addon manually, but I'm not sure why the app wouldn't install some files: https://www.curseforge.com/wow/addons/xrp/files/2861445
Do you have any other addon running and if you do, have you tried with only XRP enabled ?

**Comment by Solanya** [comment]
Reproduced the issue, will have a fix tomorrow.
