### ISSUE TITLE
Missing Embeds.xml for LibRPMedia

### ISSUE THREAD

**Issue by Arrhae** [wow-rp-addons/XRP#33]
The packaged version of XRP 2.0.9 on CurseForge is missing Libraries/LibRPMedia/Embeds.xml

```
Message: Couldn't open Interface\AddOns\XRP\Libraries\LibRPMedia\Embeds.xml
Time: Tue Nov 17 15:06:18 2020
Count: 5
```

**Comment by Solanya** [comment]
Oops, sorry about that, released a new version with it. 🤦
