### ISSUE TITLE
On launch of game in 9.2.0

### ISSUE THREAD

**Issue by Wyr3d** [wow-rp-addons/XRP#34]
Message: Interface\AddOns\XRP\Interface\Buttons\Minimap.lua:50: attempt to index field 'player' (a nil value)
Time: Sun Mar 13 12:45:56 2022
Count: 1
Stack: Interface\AddOns\XRP\Interface\Buttons\Minimap.lua:50: attempt to index field 'player' (a nil value)
[string "@Interface\AddOns\XRP\Interface\Buttons\Minimap.lua"]:50: in function <Interface\AddOns\XRP\Interface\Buttons\Minimap.lua:35>
[string "@Interface\AddOns\XRP\Interface\Buttons\Minimap.lua"]:274: in function <Interface\AddOns\XRP\Interface\Buttons\Minimap.lua:250>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\XRP\Backend\Settings\Settings.lua"]:126: in function <Interface\AddOns\XRP\Backend\Settings\Settings.lua:124>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\XRP\Backend\GameEvents.lua"]:70: in function <Interface\AddOns\XRP\Backend\GameEvents.lua:67>

Locals: <none>

**Comment by Wyr3d** [comment]
Also this one:

Message: Interface\AddOns\XRP\Interface\Buttons\Minimap.lua:50: attempt to index field 'player' (a nil value)
Time: Sun Mar 13 12:45:56 2022
Count: 1
Stack: Interface\AddOns\XRP\Interface\Buttons\Minimap.lua:50: attempt to index field 'player' (a nil value)
[string "@Interface\AddOns\XRP\Interface\Buttons\Minimap.lua"]:50: in function <Interface\AddOns\XRP\Interface\Buttons\Minimap.lua:35>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\XRP\Backend\GameEvents.lua"]:70: in function <Interface\AddOns\XRP\Backend\GameEvents.lua:67>

Locals: <none>

**Comment by Solanya** [comment]
Just released 2.0.10 which should deal with the issue. If you still have issues after updating, let me know.
