### ISSUE TITLE
LUA ERROR - Popped up randomly

### ISSUE THREAD

**Issue by Wyr3d** [wow-rp-addons/XRP#37]
Message: ...rface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua:130: AddOn_Chomp: Recieved an addon message that cannot be parsed, check your addons for updates. (This message will only display once per session, but there may be more unusable addon messages.)
Time: Thu Sep  1 13:45:16 2022
Count: 1
Stack: ...rface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua:130: AddOn_Chomp: Recieved an addon message that cannot be parsed, check your addons for updates. (This message will only display once per session, but there may be more unusable addon messages.)
[string "=[C]"]: ?
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua"]:130: in function <...rface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua:97>
[string "@Interface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua"]:535: in function <...rface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua:533>

Locals:

**Comment by Solanya** [comment]
Indeed I forgot to update a library for the last few versions and we deprecated it assuming nobody would be running it anymore. Will fix ASAP.

**Comment by Solanya** [comment]
This should now be fixed with 2.0.12.
