### ISSUE TITLE
LUA Error on Worgen transform (both ways)

### ISSUE THREAD

**Issue by Wyr3d** [wow-rp-addons/XRP#40]
Error No 1

Message: Interface/AddOns/FleecingTip/Main.lua:83: GameTooltip doesn't have a "OnTooltipSetItem" script
Time: Sat Nov 19 00:37:19 2022
Count: 1
Stack: Interface/AddOns/FleecingTip/Main.lua:83: GameTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `GetScript'
[string "@Interface/AddOns/FleecingTip/Main.lua"]:83: in function `FT_HookTooltip'
[string "@Interface/AddOns/FleecingTip/Main.lua"]:554: in function `FT_OnLoad'
[string "*Main.xml:7_OnLoad"]:1: in function <[string "*Main.xml:7_OnLoad"]:1>

Locals: (*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:338
 shoppingTooltips = <table> {
 }
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 updateTooltipTimer = 0.200000
 ItemTooltip = Frame {
 }
 StatusBar = GameTooltipStatusBar {
 }
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = GameTooltipTextRight1 {
 }
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAchievementByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsItemComparison = true
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 RefreshData = <function> defined @Interface/FrameXML/GameTooltip.lua:933
 SetTransmo
 
Error No 2

Message: Interface/AddOns/XRP/Backend/Automation.lua:83: attempt to call global 'HasAlternateForm' (a nil value)
Time: Sat Nov 19 00:39:52 2022
Count: 7
Stack: Interface/AddOns/XRP/Backend/Automation.lua:83: attempt to call global 'HasAlternateForm' (a nil value)
[string "@Interface/AddOns/XRP/Backend/Automation.lua"]:83: in function <Interface/AddOns/XRP/Backend/Automation.lua:65>
[string "@Interface/AddOns/XRP/Backend/Automation.lua"]:171: in function <Interface/AddOns/XRP/Backend/Automation.lua:169>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/XRP/Backend/GameEvents.lua"]:70: in function <Interface/AddOns/XRP/Backend/GameEvents.lua:67>

Locals: <none>

**Comment by Solanya** [comment]
First error is unrelated to XRP, it mentions FleecingTip which seems abandoned.
Will fix the second one and see if I can quickly add Dracthyr to it.

**Comment by Wyr3d** [comment]
Fair enough. I thought I had disabled Fleecing Tip XD

**Comment by Solanya** [comment]
Should be fixed with 2.0.17
