### ISSUE TITLE
Tooltip Not Working

### ISSUE THREAD

**Issue by LanceTopsail** [wow-rp-addons/XRP#43]
Hello!

With the recent patch, it appears that the XRP Tooltip is no longer working when the option to replace the default tooltip for players and pets is selected. Screenshots below. 

Let me know if I can help further!

![XRP tooltip issue](https://github.com/wow-rp-addons/XRP/assets/139515089/e98cfac1-4868-4960-afaf-a28360147a50)
![XRP Replace Tooltip Issue](https://github.com/wow-rp-addons/XRP/assets/139515089/efacd630-1fa6-4fba-bee5-1264fbcf93c5)

**Comment by Solanya** [comment]
Indeed, I tried the UI and missed the tooltip not working when I ran it on PTR. Will fix shortly.

**Comment by LanceTopsail** [comment]
Update fixed the issue - You rock!
